defaults:
  - model/base.yaml
  - model: stylegan-v

  # Import dataset common and overwrite it with the custom one
  - dataset/base.yaml
  - dataset: ffs

  - sampling/base.yaml
  - sampling: random

  - env/base.yaml
  - env: local
  - infra.yaml
  - training/base.yaml

# MonoX compatibility - allows CLI overrides
exp_suffix: null
num_gpus: 1

# Visualizer settings for MonoX
visualizer:
  save_every_kimg: 50
  output_dir: previews
