defaults:
  - model/base.yaml
  - model: stylegan-v

  # Import dataset common and overwrite it with the custom one
  - dataset/base.yaml
  - dataset: ffs

  - sampling/base.yaml
  - sampling: random

  - env/base.yaml
  - env: local
  # - infra.yaml  # Commented out to avoid SLURM dependencies in Colab
  - training/base.yaml
  - _self_

# MonoX compatibility - allows CLI overrides
exp_suffix: null
num_gpus: 1

# Experiment naming for StyleGAN-V
experiment_name: ${dataset.name}_${model.name}_${sampling.name}
git_hash: "unknown"  # Git hash for reproducibility tracking
experiment_name_with_hash: ${experiment_name}_${git_hash}  # Full experiment identifier
experiments_dir: /content/MonoX/experiments  # Top-level experiments directory
project_release_dir: /content/MonoX/experiments/${experiment_name_with_hash}  # Training output directory

# Dataset settings for MonoX CLI overrides
dataset:
  path: null
  name: ffs  # Dataset name for experiment naming
  resolution: 1024
  c_dim: 0  # Conditional dimension (0 for unconditional generation)
  fps: 25   # Frames per second for video generation
  max_num_frames: 16  # Maximum number of frames per video

# Training settings for MonoX CLI overrides  
training:
  kimg: 3000
  snap: 250

# Visualizer settings for MonoX
visualizer:
  save_every_kimg: 50
  output_dir: previews

# Sampling settings for MonoX CLI overrides
sampling:
  name: random  # Sampling strategy name for experiment naming
  truncation_psi: 1.0
  num_frames_per_video: 16  # Number of frames to generate per video
  max_dist: 16  # Maximum distance between frames for sampling

# Model settings to ensure interpolations work
model:
  name: stylegan-v  # Model name for experiment naming
  generator:
    time_enc:
      min_period_len: 16

# Environment settings for StyleGAN-V execution
env:
  project_path: /content/MonoX/.external/stylegan-v
  python_bin: python3
  experiments_dir: /content/MonoX/experiments  # Directory for experiment outputs
  datasets_dir: /content/drive/MyDrive/MonoX/dataset  # Directory containing datasets
  before_train_commands: []  # Commands to run before training (empty for Colab)
  slurm_constraint: null  # No SLURM constraints in Colab environment
