defaults:
  - model/base.yaml
  - model: stylegan-v

  # Import dataset common and overwrite it with the custom one
  - dataset/base.yaml
  - dataset: ffs

  - sampling/base.yaml
  - sampling: random

  - env/base.yaml
  - env: local
  - infra.yaml
  - training/base.yaml
  - _self_

# MonoX compatibility - allows CLI overrides
exp_suffix: null
num_gpus: 1

# Dataset settings for MonoX CLI overrides
dataset:
  path: null
  name: ffs  # Dataset name for experiment naming
  resolution: 1024
  c_dim: 0  # Conditional dimension (0 for unconditional generation)
  fps: 25   # Frames per second for video generation
  max_num_frames: 16  # Maximum number of frames per video

# Training settings for MonoX CLI overrides  
training:
  kimg: 3000
  snap: 250

# Visualizer settings for MonoX
visualizer:
  save_every_kimg: 50
  output_dir: previews

# Sampling settings for MonoX CLI overrides
sampling:
  truncation_psi: 1.0
  num_frames_per_video: 16  # Number of frames to generate per video
  max_dist: 16  # Maximum distance between frames for sampling

# Model settings to ensure interpolations work
model:
  generator:
    time_enc:
      min_period_len: 16

# Environment settings for StyleGAN-V execution
env:
  project_path: /content/MonoX/.external/stylegan-v
  python_bin: python3
